// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customActionData.proto

#ifndef PROTOBUF_customActionData_2eproto__INCLUDED
#define PROTOBUF_customActionData_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "command.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_customActionData_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void InitDefaultsCustomActionDataImpl();
void InitDefaultsCustomActionData();
inline void InitDefaults() {
  InitDefaultsCustomActionData();
}
}  // namespace protobuf_customActionData_2eproto
namespace com {
namespace panelsw {
namespace ca {
class CustomActionData;
class CustomActionDataDefaultTypeInternal;
extern CustomActionDataDefaultTypeInternal _CustomActionData_default_instance_;
}  // namespace ca
}  // namespace panelsw
}  // namespace com
namespace com {
namespace panelsw {
namespace ca {

// ===================================================================

class CustomActionData : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:com.panelsw.ca.CustomActionData) */ {
 public:
  CustomActionData();
  virtual ~CustomActionData();

  CustomActionData(const CustomActionData& from);

  inline CustomActionData& operator=(const CustomActionData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CustomActionData(CustomActionData&& from) noexcept
    : CustomActionData() {
    *this = ::std::move(from);
  }

  inline CustomActionData& operator=(CustomActionData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const CustomActionData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CustomActionData* internal_default_instance() {
    return reinterpret_cast<const CustomActionData*>(
               &_CustomActionData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(CustomActionData* other);
  friend void swap(CustomActionData& a, CustomActionData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CustomActionData* New() const PROTOBUF_FINAL { return New(NULL); }

  CustomActionData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const CustomActionData& from);
  void MergeFrom(const CustomActionData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CustomActionData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .com.panelsw.ca.Command commands = 1;
  int commands_size() const;
  void clear_commands();
  static const int kCommandsFieldNumber = 1;
  const ::com::panelsw::ca::Command& commands(int index) const;
  ::com::panelsw::ca::Command* mutable_commands(int index);
  ::com::panelsw::ca::Command* add_commands();
  ::google::protobuf::RepeatedPtrField< ::com::panelsw::ca::Command >*
      mutable_commands();
  const ::google::protobuf::RepeatedPtrField< ::com::panelsw::ca::Command >&
      commands() const;

  // string id = 2;
  void clear_id();
  static const int kIdFieldNumber = 2;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // @@protoc_insertion_point(class_scope:com.panelsw.ca.CustomActionData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::com::panelsw::ca::Command > commands_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  mutable int _cached_size_;
  friend struct ::protobuf_customActionData_2eproto::TableStruct;
  friend void ::protobuf_customActionData_2eproto::InitDefaultsCustomActionDataImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CustomActionData

// repeated .com.panelsw.ca.Command commands = 1;
inline int CustomActionData::commands_size() const {
  return commands_.size();
}
inline const ::com::panelsw::ca::Command& CustomActionData::commands(int index) const {
  // @@protoc_insertion_point(field_get:com.panelsw.ca.CustomActionData.commands)
  return commands_.Get(index);
}
inline ::com::panelsw::ca::Command* CustomActionData::mutable_commands(int index) {
  // @@protoc_insertion_point(field_mutable:com.panelsw.ca.CustomActionData.commands)
  return commands_.Mutable(index);
}
inline ::com::panelsw::ca::Command* CustomActionData::add_commands() {
  // @@protoc_insertion_point(field_add:com.panelsw.ca.CustomActionData.commands)
  return commands_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::com::panelsw::ca::Command >*
CustomActionData::mutable_commands() {
  // @@protoc_insertion_point(field_mutable_list:com.panelsw.ca.CustomActionData.commands)
  return &commands_;
}
inline const ::google::protobuf::RepeatedPtrField< ::com::panelsw::ca::Command >&
CustomActionData::commands() const {
  // @@protoc_insertion_point(field_list:com.panelsw.ca.CustomActionData.commands)
  return commands_;
}

// string id = 2;
inline void CustomActionData::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CustomActionData::id() const {
  // @@protoc_insertion_point(field_get:com.panelsw.ca.CustomActionData.id)
  return id_.GetNoArena();
}
inline void CustomActionData::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.panelsw.ca.CustomActionData.id)
}
#if LANG_CXX11
inline void CustomActionData::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.panelsw.ca.CustomActionData.id)
}
#endif
inline void CustomActionData::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.panelsw.ca.CustomActionData.id)
}
inline void CustomActionData::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.panelsw.ca.CustomActionData.id)
}
inline ::std::string* CustomActionData::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:com.panelsw.ca.CustomActionData.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CustomActionData::release_id() {
  // @@protoc_insertion_point(field_release:com.panelsw.ca.CustomActionData.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CustomActionData::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:com.panelsw.ca.CustomActionData.id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace ca
}  // namespace panelsw
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_customActionData_2eproto__INCLUDED
